-- Create separate schemas for each service.
CREATE SCHEMA IF NOT EXISTS "user";
CREATE SCHEMA IF NOT EXISTS catalog;
CREATE SCHEMA IF NOT EXISTS payment;
CREATE SCHEMA IF NOT EXISTS spot;
CREATE SCHEMA IF NOT EXISTS errand;

SET search_path TO "user";

CREATE TYPE auth_session_status AS ENUM ('active', 'revoked', 'expired');
CREATE TYPE member_role AS ENUM ('user', 'admin');
CREATE TYPE member_status AS ENUM ('active', 'restricted', 'banned', 'deleted');

CREATE TABLE user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feishu_open_id TEXT NOT NULL UNIQUE,
    role member_role NOT NULL DEFAULT 'user',
    status member_status NOT NULL DEFAULT 'active',
    display_name TEXT NOT NULL,
    avatar_url TEXT NOT NULL DEFAULT '',
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE auth_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES user_account(id),
    refresh_token_hash TEXT NOT NULL UNIQUE,
    status auth_session_status NOT NULL DEFAULT 'active',
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE member_address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES user_account(id) ON DELETE CASCADE,
    recipient_name TEXT NOT NULL,
    recipient_phone TEXT NOT NULL,
    province TEXT NOT NULL DEFAULT '',
    city TEXT NOT NULL DEFAULT '',
    district TEXT NOT NULL DEFAULT '',
    detail_address TEXT NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_member_default_address
ON member_address(user_id)
WHERE is_default = true;


SET search_path TO catalog;

CREATE TYPE catalog_status AS ENUM ('draft', 'active', 'hidden', 'removed');

CREATE TABLE catalog_store (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT NOT NULL,
    logo_url TEXT NOT NULL DEFAULT '',
    theme_color TEXT NOT NULL DEFAULT '#FFFFFF',
    status catalog_status NOT NULL DEFAULT 'active',
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (name, address)
);

CREATE TABLE catalog_product_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    price_cents INTEGER NOT NULL CHECK (price_cents >= 0),
    store_id BIGINT NOT NULL REFERENCES catalog_store(id),
    status catalog_status NOT NULL DEFAULT 'active',
    created_by_user_id BIGINT NOT NULL,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE catalog_product_barcode (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_template_id BIGINT NOT NULL REFERENCES catalog_product_template(id) ON DELETE CASCADE,
    barcode TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(barcode, product_template_id)
);

CREATE TABLE catalog_product_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_template_id BIGINT NOT NULL REFERENCES catalog_product_template(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);


SET search_path TO payment;

CREATE TYPE payment_channel AS ENUM ('wechat', 'alipay');
CREATE TYPE payment_bill_status AS ENUM ('unpaid', 'submitted', 'completed', 'closed');

CREATE TABLE payment_qr_code (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    channel payment_channel NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_payment_qr_owner_channel
ON payment_qr_code(owner_id, channel);

CREATE TABLE payment_bill (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_no TEXT NOT NULL UNIQUE,
    payer_id BIGINT NOT NULL,
    payee_id BIGINT NOT NULL,
    source_type TEXT,
    source_id BIGINT,
    amount_cents INTEGER NOT NULL CHECK (amount_cents >= 0),
    verify_code TEXT NOT NULL CHECK (verify_code ~ '^[0-9]{4}$'),
    status payment_bill_status NOT NULL DEFAULT 'unpaid',
    channel payment_channel,
    serial_number TEXT NOT NULL DEFAULT '', -- Extra note when the verification code is missing
    submitted_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Idempotency: one bill per source and payer combination.
CREATE UNIQUE INDEX uq_payment_bill_source
ON payment_bill(source_type, source_id, payer_id)
WHERE source_type IS NOT NULL AND source_id IS NOT NULL;

CREATE TABLE payment_confirmation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id BIGINT NOT NULL REFERENCES payment_bill(id) ON DELETE CASCADE,
    operator_id BIGINT NOT NULL,
    from_status payment_bill_status NOT NULL,
    to_status payment_bill_status NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);


SET search_path TO errand;

CREATE TYPE errand_demand_status AS ENUM (
    'open',
    'shopping',
    'pending_distributing',
    'distributing',
    'pending_payment',
    'completed',
    'cancelled'
);

CREATE TYPE errand_demand_item_status AS ENUM (
    'open',
    'shopping',
    'pending_distributing',
    'distributing',
    'pending_payment',
    'completed',
    'cancelled'
);

CREATE TYPE errand_task_status AS ENUM (
    'shopping',
    'pending_distributing',
    'distributing',
    'collecting_payment',
    'completed',
    'cancelled'
);

CREATE TABLE errand_demand (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id BIGINT NOT NULL,
    store_id BIGINT NOT NULL,
    status errand_demand_status NOT NULL DEFAULT 'open',
    deadline TIMESTAMPTZ NOT NULL CHECK (deadline > now()),
    task_id BIGINT,
    split_from_demand_id BIGINT REFERENCES errand_demand(id),
    shopping_start_at TIMESTAMPTZ,
    shopping_completed_at TIMESTAMPTZ,
    distribution_completed_at TIMESTAMPTZ,
    payment_completed_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE errand_demand_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    errand_demand_id BIGINT NOT NULL REFERENCES errand_demand(id) ON DELETE CASCADE,
    requester_id BIGINT NOT NULL,
    store_id BIGINT NOT NULL,
    product_template_id BIGINT NOT NULL,
    estimated_unit_price_cents INTEGER NOT NULL CHECK (estimated_unit_price_cents >= 0),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    service_fee_per_unit_cents INTEGER NOT NULL CHECK (service_fee_per_unit_cents >= 0),
    status errand_demand_item_status NOT NULL DEFAULT 'open',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(errand_demand_id, product_template_id)
);

CREATE TABLE errand_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_no TEXT NOT NULL UNIQUE,
    captain_id BIGINT NOT NULL,
    store_id BIGINT NOT NULL,
    status errand_task_status NOT NULL DEFAULT 'shopping',
    packaging_fee_cents INTEGER NOT NULL DEFAULT 0 CHECK (packaging_fee_cents >= 0),
    shopping_completed_at TIMESTAMPTZ,
    distribution_completed_at TIMESTAMPTZ,
    payment_completed_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE errand_task_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL REFERENCES errand_task(id) ON DELETE CASCADE,
    product_template_id BIGINT NOT NULL,
    title_snapshot TEXT NOT NULL,
    description_snapshot TEXT NOT NULL DEFAULT '',
    image_url_snapshot TEXT NOT NULL DEFAULT '',
    required_quantity INTEGER NOT NULL CHECK (required_quantity > 0),
    purchased_quantity INTEGER CHECK (purchased_quantity IS NULL OR purchased_quantity >= 0),
    non_purchase_reason TEXT NOT NULL DEFAULT '',
    actual_unit_price_cents INTEGER CHECK (actual_unit_price_cents >= 0),
    deadline TIMESTAMPTZ NOT NULL,
    handled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(task_id, product_template_id, deadline)
);

CREATE TABLE errand_task_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL REFERENCES errand_task(id) ON DELETE CASCADE,
    task_item_id BIGINT NOT NULL REFERENCES errand_task_item(id) ON DELETE CASCADE,
    demand_item_id BIGINT NOT NULL UNIQUE REFERENCES errand_demand_item(id),
    purchaser_id BIGINT NOT NULL,
    distributed_quantity INTEGER NOT NULL DEFAULT 0 CHECK (distributed_quantity >= 0),
    service_fee_per_unit_cents INTEGER NOT NULL CHECK (service_fee_per_unit_cents >= 0),
    payment_bill_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE errand_price_change_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_item_id BIGINT NOT NULL REFERENCES errand_task_item(id) ON DELETE CASCADE,
    operator_id BIGINT NOT NULL,
    old_unit_price_cents INTEGER,
    new_unit_price_cents INTEGER NOT NULL CHECK (new_unit_price_cents >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE errand_action_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL REFERENCES errand_task(id) ON DELETE CASCADE,
    actor_id BIGINT NOT NULL,
    target_type TEXT NOT NULL,
    target_id BIGINT NOT NULL,
    action TEXT NOT NULL,
    before_state JSONB NOT NULL DEFAULT '{}'::jsonb,
    after_state JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

SET search_path TO spot;

CREATE TYPE spot_order_status AS ENUM ('pending_payment', 'paid', 'completed', 'cancelled');
CREATE TYPE stock_ledger_reason AS ENUM ('publish', 'order_lock', 'order_cancel', 'manual_adjust');

CREATE TABLE spot_goods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id BIGINT NOT NULL,
    store_id BIGINT NOT NULL,
    product_template_id BIGINT NOT NULL,
    sale_price_cents INTEGER NOT NULL CHECK (sale_price_cents >= 0),
    stock_total INTEGER NOT NULL CHECK (stock_total >= 0),
    closed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE spot_stock_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL REFERENCES spot_goods(id),
    delta INTEGER NOT NULL,
    reason stock_ledger_reason NOT NULL DEFAULT 'publish',
    ref_type TEXT NOT NULL DEFAULT '', -- Service name that changed the stock amount
    ref_id BIGINT, -- Business identifier for the stock change
    operator_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE spot_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no TEXT NOT NULL UNIQUE,
    purchaser_id BIGINT NOT NULL,
    listing_id BIGINT NOT NULL REFERENCES spot_goods(id),
    product_template_id BIGINT NOT NULL,
    title_snapshot TEXT NOT NULL,
    description_snapshot TEXT NOT NULL DEFAULT '',
    image_url_snapshot TEXT NOT NULL DEFAULT '',
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price_cents INTEGER NOT NULL CHECK (unit_price_cents >= 0),
    total_amount_cents INTEGER NOT NULL CHECK (total_amount_cents >= 0),
    payment_bill_id BIGINT,
    status spot_order_status NOT NULL DEFAULT 'pending_payment',
    paid_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

